### ISSUE TITLE
GUI crash on resizing virtual detectors

### ISSUE THREAD

**Issue by HamishGBrown** [py4dstem/py4DSTEM#82]
The GUI keeps crashing when I'm loading a 4D-STEM dataset and I select a large region of the diffraction pattern for the virtual detector. It might be related to the fact that I'm selecting regions outside the actual dimensions of the array (though most of the time that seems to be fine) or, more likely, that there's a few corrupted pixels in my dataset, which have been erroneously assigned very large values and this causes the an overflow and crash. The Traceback message is below:

```
Traceback (most recent call last):
  File "/home/ncem/anaconda3/lib/python3.7/site-packages/pyqtgraph/graphicsItems/InfiniteLine.py", line 215, in boundingRect
    px = self.pixelLength(direction=Point(1,0), ortho=True)  ## get pixel length orthogonal to the line
  File "/home/ncem/anaconda3/lib/python3.7/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 270, in pixelLength
    return orthoV.length()
  File "/home/ncem/anaconda3/lib/python3.7/site-packages/pyqtgraph/Point.py", line 108, in length
    return (self[0]**2 + self[1]**2) ** 0.5
OverflowError: (34, 'Numerical result out of range')
Aborted (core dumped)
```

Can share the dataset if necessary though it's a 2 GB file.

**Comment by sezelt** [comment]
Closing since the GUI has been removed
